### ISSUE TITLE
Availability in PGDG repo

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/selinux-pgsql-pgdg#10]
Hi,

Unless you folks object, I'd like to add this package to PGDG repos. What do you think?

**Comment by orgrim** [comment]
Hi,

No objections here, please do. Thanks.

Regards

**Comment by daamien** [comment]
Closing this issue:

The package is now available in the PGDG repo
https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/main/common/pgdg-pgsql-selinux/main/selinux-pgsql-pgdg.spec;h=d92e1e5d4e5ac5d475c207da05a2ff8ab10bd4d7;hb=19a463946219770f66544c5d55d73c09ee2a075d
